In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.DataFrame({
    'x0': [1,2,3,4,5],
    'x1':[0.01,-0.01,0.25,-4.1, 0.],
    'y':[-1.5,0., 3.6, 1.3, -2.]
})

In [3]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [4]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [5]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

To convert back to a DataFrame

In [6]:
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])

In [7]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [8]:
df3 = data.copy()

In [9]:
df3['strings'] =['a', 'b', 'c', 'd', 'e']

In [10]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [11]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [12]:
model_cols =['x0','x1']
data.loc[:,model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [13]:
data["category"] = pd.Categorical(["a", "b", "a", "a", "b"], categories=["a", "b"])

In [14]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [17]:
dummies = pd.get_dummies(data.category, prefix="category")

In [18]:
dummies

category_a  category_b
0        True       False
1       False        True
2        True       False
3        True       False
4       False        True

In [19]:
data_with_dummies = data.drop('category', axis=1).join(dummies)

In [20]:
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5        True       False
1   2 -0.01  0.0       False        True
2   3  0.25  3.6        True       False
3   4 -4.10  1.3        True       False
4   5  0.00 -2.0       False        True

In [21]:
!pip install statsmodels

   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB 487.6 kB/s eta 0:00:21
    --------------------------------------- 0.1/9.8 MB 1.0 MB/s eta 0:00:10
    --------------------------------------- 0.2/9.8 MB 1.4 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/9.8 MB 2.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/9.8 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.8 MB 4.6 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.8 MB 4.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.8 MB 5.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.8 MB 5.3 MB/s eta 0:00:02
   ----------- ---------------------------- 2.7/9.8 MB 5.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.2/9.8 MB 6.0 MB/s eta 0:00:02
   -------------- ------

In [22]:
data = pd.DataFrame({"x0": [1, 2, 3, 4, 5], "x1": [0.01, -0.01, 0.25, -4.1, 0.], "y": [-1.5, 0., 3.6, 1.3, -2.]})

In [23]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [24]:
import patsy

y,x = patsy.dmatrices("y ~ x0 + x1", data)

In [25]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [26]:
x

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

These design matrices can be used as input to statistical modeling libraries like statsmodels for fitting the linear regression model.

In [27]:
type(y)

patsy.design_info.DesignMatrix

In [28]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [29]:
np.asarray(x)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [30]:
patsy.dmatrices("y ~ x0 + x1 + 0", data)

(DesignMatrix with shape (5, 1)
      y
   -1.5
    0.0
    3.6
    1.3
   -2.0
   Terms:
     'y' (column 0),
 DesignMatrix with shape (5, 2)
   x0     x1
    1   0.01
    2  -0.01
    3   0.25
    4  -4.10
    5   0.00
   Terms:
     'x0' (column 0)
     'x1' (column 1))

The patsy object can be passed directly into algorithms like numpy.linalg.lstsq which performs an ordinary least squares regression.

In [33]:
coef, resid, _, _ = np.linalg.lstsq(x, y)

C:\Users\bishn\AppData\Local\Temp\ipykernel_9184\2233073461.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid, _, _ = np.linalg.lstsq(x, y)


In [34]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [35]:
resid

array([19.63791494])

In [41]:
coef[0] + coef[1] * 3+coef[2]*0.25

array([0.00922688])

In [40]:
coef[0]

array([0.31290976])

In [42]:
coef = pd.Series(coef.squeeze(), index=x.design_info.column_names)

In [43]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [44]:
y, X = patsy.dmatrices("y ~ x0 + np.log(np.abs(x1) + 1)", data)

In [45]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [46]:
y, X = patsy.dmatrices("y ~ standardize(x0) + center(x1)", data)

In [47]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [48]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]
})

Patsy.build_design_matrices function can apply transformations to new out-of-sample data using the saved information from original in-sample dataset.
The model metadata is retained in the design_info attribute.
Here it used metadata obtined from design matrices of X in new data.

In [49]:
new_X = patsy.build_design_matrices([X.design_info], new_data)

In [53]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

"+" symbol in the context of patsy formulas does not mean addition, when you want to add columns from a dataset by name, you must wrap them in the special I dunction.

In [54]:
y, X = patsy.dmatrices("y ~ I(x0 + x1)", data)

In [55]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

Categorical Data and Patsy

In [56]:
data = pd.DataFrame({
    'key1' : ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'a'],
    'key2' : [0,1,0,1,0,1,0,0],
    'v1': [1,2,3,4,5,6,7,8],
    'v2': [-1,0,2.5,-0.5,4.0,-1.2,0.2,-2.0]
})

In [57]:
y, X = patsy.dmatrices("v2 ~ key1", data)

In [59]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          0
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [60]:
y , X = patsy.dmatrices("v2 ~ key1 + 0", data)

In [61]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        1        0
  Terms:
    'key1' (columns 0:2)

Numerical Columns can be interpreted as categorical with the C function

In [66]:
y, X = patsy.dmatrices('v2  ~ C(key2) + 0', data)

In [67]:
X

DesignMatrix with shape (8, 2)
  C(key2)[0]  C(key2)[1]
           1           0
           0           1
           1           0
           0           1
           1           0
           0           1
           1           0
           1           0
  Terms:
    'C(key2)' (columns 0:2)

In [68]:
data["key2"] = data["key2"].map({0: 'zero', 1: 'one'})

In [69]:
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    a  zero   8 -2.0

In [72]:
y, X = patsy.dmatrices("v2 ~ key1 + key2 + key1:key2 + 0", data)

In [73]:
X

DesignMatrix with shape (8, 4)
  key1[a]  key1[b]  key2[T.zero]  key1[T.b]:key2[T.zero]
        1        0             1                       0
        1        0             0                       0
        0        1             1                       1
        0        1             0                       0
        1        0             1                       0
        0        1             0                       0
        1        0             1                       0
        1        0             1                       0
  Terms:
    'key1' (columns 0:2)
    'key2' (column 2)
    'key1:key2' (column 3)

In [74]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [75]:
rng = np.random.default_rng(seed=12345)

In [76]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size
    return mean + np.sqrt(variance) * rng.standard_normal(size)

In [77]:
N=100
X = np.c_[dnorm(0,0.4,N), dnorm(0,0.6,N), dnorm(0,0.2,N)]
eps = dnorm(0,0.1,N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

In [78]:
y

array([-0.59952668, -0.58845445,  0.18563386, -0.00747657, -0.01537445,
       -0.48405182,  0.03006418,  0.21745535,  0.09733398,  0.29428061,
       -0.55821726,  0.39275937, -0.88717278, -0.14095687, -0.24884462,
       -0.11545172,  0.49031861, -0.53928623,  0.01003077, -0.12181392,
       -0.40652191, -0.26296953,  0.24121365, -0.01486882, -0.8269326 ,
        0.85796862, -0.1581605 ,  0.3229089 , -0.3182448 , -0.25177682,
        0.01201277, -0.27692688,  0.48915537,  0.02713607,  0.32623478,
       -0.67005187, -0.43638036,  0.19876113,  0.29108143,  1.22925781,
       -0.13454699,  0.11618133, -0.28334439,  0.82639714,  0.65173309,
        0.36932726,  0.46060306, -0.36001815, -0.67943794, -0.32391053,
        0.22890353,  0.33392927, -0.02893472,  0.3514912 ,  0.4104761 ,
        0.02342595, -0.08816253, -0.42223253,  0.95031167, -0.84319881,
       -0.17742481, -0.58276729, -0.04786858,  0.49981461, -0.40998529,
       -0.06505591, -0.11920059, -0.73782536,  0.11294051, -0.50

In [79]:
X_model = sm.add_constant(X)

In [80]:
X_model[:5]

array([[ 1.        , -0.90050602, -0.18942958, -1.0278702 ],
       [ 1.        ,  0.79925205, -1.54598388, -0.32739708],
       [ 1.        , -0.55065483, -0.12025429,  0.32935899],
       [ 1.        , -0.16391555,  0.82403985,  0.20827485],
       [ 1.        , -0.04765129, -0.21314698, -0.04824364]])

In [82]:
model = sm.OLS(y,X) #ordinary least squares

In [83]:
result = model.fit()
result.params

array([0.06681503, 0.26803235, 0.45052319])

In [84]:
print(result.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.469
Model:                            OLS   Adj. R-squared (uncentered):              0.452
Method:                 Least Squares   F-statistic:                              28.51
Date:                Tue, 07 May 2024   Prob (F-statistic):                    2.66e-13
Time:                        00:03:57   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [88]:
0.06681503 * 0.79925205 + 0.26803235 * -1.54598388 + 0.45052319 * -0.32035429 

-0.5052986793811916

In [89]:
train = pd.read_csv("D:/wesm/pydata-book/datasets/titanic/train.csv")

In [92]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [93]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [94]:
test = pd.read_csv("D:/wesm/pydata-book/datasets/titanic/test.csv")

In [95]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [96]:
impute_values = train["Age"].median()

In [97]:
train["Age"] = train["Age"].fillna(impute_values)
test["Age"] = test["Age"].fillna(impute_values)

In [99]:
train["IsFemale"] = (train["Sex"] == "female").astype(int)

In [100]:
test["IsFemale"] = (test["Sex"] == "female").astype(int)

In [102]:
train["IsFemale"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: IsFemale, Length: 891, dtype: int32

In [103]:
predictors = ["IsFemale", "Pclass", "Age"]

In [106]:
X_train = train[predictors].to_numpy()
X_test = test[predictors].to_numpy()
y_train = train["Survived"].to_numpy()
# y_test = test["Survived"].to_numpy()

In [107]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
 11  IsFemale     418 non-null    int32  
dtypes: float64(2), int32(1), int64(4), object(5)
memory usage: 37.7+ KB


In [108]:
X_train[:5]

array([[ 0.,  3., 22.],
       [ 1.,  1., 38.],
       [ 1.,  3., 26.],
       [ 1.,  1., 35.],
       [ 0.,  3., 35.]])

In [109]:
y_train[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [116]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [117]:
model.fit(X_train, y_train)

LogisticRegression()

In [118]:
y_predict = model.predict(X_test)

In [119]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [120]:
from sklearn.linear_model import LogisticRegressionCV

model_cv = LogisticRegressionCV(Cs=10)

model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [122]:
from sklearn.model_selection import cross_val_score

In [124]:
scores = cross_val_score(model_cv, X_train, y_train, cv=5)

In [125]:
scores

array([0.70949721, 0.78089888, 0.79213483, 0.76966292, 0.79775281])

In [126]:
model_cv.C_[0]

21.54434690031882

In [129]:
from sklearn.model_selection import GridSearchCV

# Define a grid of C values
param_grid = {'C': np.arange(1,30)}

# Perform grid search with cross-validation
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Print the best C value and corresponding score
print("Best C value:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)


Best C value: {'C': 1}
Best score: 0.7867553825874082


C is the regularization parameter. Higher values of C indicate weaker regularization (less penalty), while lower values of C indicate stronger regularization (more penalty).