In [2]:
!pip install opencv-python

   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB 991.0 kB/s eta 0:00:39
   ---------------------------------------- 0.1/38.1 MB 656.4 kB/s eta 0:00:58
   ---------------------------------------- 0.1/38.1 MB 1.1 MB/s eta 0:00:36
   ---------------------------------------- 0.2/38.1 MB 1.1 MB/s eta 0:00:36
   ---------------------------------------- 0.4/38.1 MB 1.6 MB/s eta 0:00:24
   ---------------------------------------- 0.5/38.1 MB 1.7 MB/s eta 0:00:22
    --------------------------------------- 0.6/38.1 MB 2.0 MB/s eta 0:00:19
    --------------------------------------- 0.8/38.1 MB 2.2 MB/s eta 0:00:18
   - -------------------------------------- 1.0/38.1 MB 2.4 MB/s eta 0:00:16
   - -------------------------------------- 1.1/38.1 MB 2.5 MB/s eta 0:00:15
   - -------------------------------------- 1.3/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.4/38.1 MB 2.7 MB/s eta 0:00:14
  

In [3]:
import cv2
import numpy as np


In [10]:
img = cv2.imread("photo.jpg")

In [5]:
type(img)

numpy.ndarray

In [6]:
img

array([[[40, 40, 40],
        [35, 35, 35],
        [37, 37, 37],
        ...,
        [52, 52, 52],
        [53, 53, 53],
        [54, 54, 54]],

       [[36, 36, 36],
        [39, 39, 39],
        [44, 44, 44],
        ...,
        [55, 55, 55],
        [58, 58, 58],
        [59, 59, 59]],

       [[35, 35, 35],
        [44, 44, 44],
        [49, 49, 49],
        ...,
        [57, 57, 57],
        [60, 60, 60],
        [62, 62, 62]],

       ...,

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        ...,
        [13, 13, 13],
        [13, 13, 13],
        [13, 13, 13]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        ...,
        [13, 13, 13],
        [13, 13, 13],
        [13, 13, 13]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        ...,
        [13, 13, 13],
        [13, 13, 13],
        [13, 13, 13]]], dtype=uint8)

In [14]:
img.shape

(206, 206, 3)

In [45]:
cv2.imshow("window",img_own)
cv2.waitKey(0)

-1

In [12]:
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [19]:
img_blue = img[:,:,0]
img_green = img[:,:,1]
img_red = img[:,:,2]

img_stack = np.hstack((img_blue,img_red,img_green))

In [21]:
img_resize = cv2.resize(img,(600,600))

In [23]:
#0 == flip along vertical axis
#1 == flip along horizontal axis
#-1 == combined effect of both

In [28]:
img_flip = cv2.flip(img,-1)

In [34]:
 img_crop = img[0:100,0:200]

In [36]:
#cv2.imwrite("name_to_keep",name_in_code)_____for saving the image

In [4]:
img_own = np.zeros((512,512,3))

In [39]:
cv2.rectangle(img_own,pt1=(100,100),pt2=(300,300),color=(0,0,255),thickness=5)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
cv2.circle(img_own,center=(100,400),radius = 10,color=(255,0,0),thickness=-1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
def draw(event,x,y,flags,params):
    if event == 1:
       cv2.rectangle(img_own,pt1=(x,y),pt2=(300,300),color=(0,0,255),thickness=5)


In [5]:
cv2.namedWindow(winname="window") 
cv2.setMouseCallback("window",draw)

In [7]:
while True:
    cv2.imshow("windows",img_own)
    if cv2.waitKey(1) & 0xFF == ord('x'):
        break
cv2.destroyAllWindows()

In [9]:
flag = False
ix=-1
iy=-1

def draw(event,x,y,flags,params):
    global flag,ix,iy
    # if event == 1:
    #     cv2.rectangle(img,pt1=(x,y),pt2=(300,300),color=(0,0,255),thickness=5)
    if event == 1:
        flag = True
        ix=x
        iy=y
        
    elif event == 0:
        if flag == True:
            cv2.rectangle(img,pt1=(ix,iy),pt2=(x,y),color=(0,255,255),thickness=3)
    
    elif event == 4:
        flag=False
        cv2.rectangle(img,pt1=(ix,iy),pt2=(x,y),color=(0,255,255),thickness=3)
        

In [10]:
flag = False
ix=-1
iy=-1

def crop(event,x,y,flags,params):
    global flag,ix,iy
    if event == 1:
        flag = True
        ix=x
        iy=y
        
    elif event == 4:
        fx=x
        fy = y
        flag = False
        cv2.rectangle(img,pt1=(ix,iy),pt2=(x,y),thickness=1,color=(0,0,0))
        
        cropped = img[iy:fy,ix:fx]
        cv2.imshow("new_wimdown",cropped)
        cv2.waitKey(0)

In [ ]:
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter("output.avi",fourcc,20.0,(640,480))

while True:
    ret, frame = cap.read()
    out.write(frame)
    img_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cv2.imshow("webcam",img_gray)
    
    if cv2.waitKey(1) & 0xFF == ord('x'):
         break
     
     
out.release()    
cv2.destroyAllWindows()